# Generated by Django 3.0.5 on 2021-12-08 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0002_topping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topping',
            options={'verbose_name_plural': 'Toppings'},
        ),
    ]
